env:
  node: true
  browser: true
  es6: true
parser: 'babel-eslint'
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-unused-vars: ["error", { "vars": "all", "args": "after-used", "ignoreRestSiblings": false }],
  require-atomic-updates: "off"
}
